flowchart TD
    Start --> |"Build()"| QueryBuilder

    QueryBuilder --> |"build()"| Create
    QueryBuilder --> |"build()"| Delete
    QueryBuilder --> |"build()"| DetachDelete
    QueryBuilder --> |"build()"| Match
    QueryBuilder --> |"build()"| Return
    QueryBuilder --> |"build()"| ReturnElement
    QueryBuilder --> |"build()"| Where

    Create --> CreateBuilder
    Delete --> |"query = DELETE"| DeleteBuilder
    DetachDelete --> |"query = DETACH DELETE"| DeleteBuilder
    Match --> MatchBuilder
    Return --> |"buildFunc = returnBuild"| ReturnBuilder
    ReturnElement --> |"buildFunc = returnElementBuild"| ReturnBuilder
    Where --> WhereBuilder

    PatternInterface(PatternInterface)
    ElementInterface(ElementInterface)
    UnbuiltPropOrVar("UnbuiltPropOrVar[T]")

    CreateBuilder --> |"build()"| PatternInterface
    DeleteBuilder --> |"buildElement()"| ElementInterface
    MatchBuilder --> |"build()"| PatternInterface
    ReturnBuilder --> |"build()"| buildFunc(buildFunc)
    WhereBuilder --> |"buildCondition()"| ConditionBuilder

    buildFunc --> returnElementBuild("returnElementBuild")
    buildFunc --> returnBuild("returnBuild")

    returnBuild --> |"buildRef()"| UnbuiltPropOrVar
    returnElementBuild --> |"buildElement()"| ElementInterface


    PatternInterface --> NodePattern
    PatternInterface -->  RelationPattern

    NodePattern --> |"buildElement()"| Node
    RelationPattern --> |"buildElement()"| Relation

    ElementInterface --> Node
    ElementInterface --> Relation

    Node --> |"ensureNodeRef()"| Builder
    Relation --> |"ensureRelationRef()"| Builder

    ConditionBuilder --> |"build()"| conditionPart("conditionPart")

    conditionPart --> propConditionPart
    conditionPart --> listPart
    conditionPart --> nestedConditionPart
    conditionPart --> rawPart
    conditionPart --> refConditionPart
    conditionPart --> anyPart

    propConditionPart --> |"buildRef()"| UnbuiltProp
    nestedConditionPart --> |"buildCondition()"| ConditionBuilder
    listPart --> |"ensureListRef()"| Builder
    anyPart --> |"ensureValueRef()"| Builder
    refConditionPart --> |"buildRef()"| UnbuiltRef

    UnbuiltPropOrVar --> UnbuiltProp
    UnbuiltPropOrVar --> UnbuiltRef

    UnbuiltRef --> |"buildElement()"| ElementInterface
    UnbuiltProp --> |"ensureTokenRef()"| Builder