flowchart TD
    StartPatternState --> |"Node()"| NodePatternState
    NodePatternState --> |"Relation()"| RelationPatternState
    RelationPatternState --> |"Node()"| CompletePatternState
    CompletePatternState --> |"Relation()"| StartPatternState

