flowchart TD
    StartPatternState --> |"Node()"| CompletePatternState
    NodePatternState --> |"Relation()"| RelationPatternState
    RelationPatternState --> |"Node()"| CompletePatternState
    CompletePatternState --> NodePatternState

